from PyQt5 import QtWidgets, QtCore
from Lab4.utils import np_array_to_pixmap
from Lab4.events import event_manager


class TransformationWidget(QtWidgets.QWidget):

    qrect_shape = QtCore.QRect(10, 25, 1245, 480)
    def __init__(self, parent=None, **kwargs) -> None:
        super().__init__(parent, **kwargs)

        self.affine_transforms_tab = QtWidgets.QWidget()
        self.affine_transforms_tab.setObjectName("tab")

        self.gridLayout = QtWidgets.QGridLayout(self.affine_transforms_tab)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.affine_transforms_tab)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_20 = QtWidgets.QFrame(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_20.sizePolicy().hasHeightForWidth())
        self.frame_20.setSizePolicy(sizePolicy)
        self.frame_20.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_20)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem4)
        self.formLayout_14 = QtWidgets.QFormLayout()
        self.formLayout_14.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_14.setObjectName("formLayout_14")
        self.label_8 = QtWidgets.QLabel(self.frame_20)
        self.label_8.setObjectName("label_8")
        self.formLayout_14.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.trans_x = QtWidgets.QLineEdit(self.frame_20)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trans_x.sizePolicy().hasHeightForWidth())
        self.trans_x.setSizePolicy(sizePolicy)
        self.trans_x.setObjectName("lineEdit_8")
        self.formLayout_14.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.trans_x)
        self.horizontalLayout_10.addLayout(self.formLayout_14)
        self.formLayout_15 = QtWidgets.QFormLayout()
        self.formLayout_15.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_15.setContentsMargins(-1, -1, 0, -1)
        self.formLayout_15.setObjectName("formLayout_15")
        self.label_9 = QtWidgets.QLabel(self.frame_20)
        self.label_9.setObjectName("label_9")
        self.formLayout_15.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.trans_y = QtWidgets.QLineEdit(self.frame_20)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trans_y.sizePolicy().hasHeightForWidth())
        self.trans_y.setSizePolicy(sizePolicy)
        self.trans_y.setObjectName("lineEdit_9")
        self.formLayout_15.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.trans_y)
        self.horizontalLayout_10.addLayout(self.formLayout_15)
        self.trans_btn = QtWidgets.QPushButton(self.frame_20)
        self.trans_btn.setObjectName("pushButton_9")
        self.horizontalLayout_10.addWidget(self.trans_btn)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem5)
        self.gridLayout_3.addWidget(self.frame_20, 0, 1, 1, 1)
        self.frame_24 = QtWidgets.QFrame(self.tab_2)
        self.frame_24.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.canvas_trans = QtWidgets.QLabel(self.frame_24)
        self.canvas_trans.setGeometry(self.qrect_shape)
        self.canvas_trans.setText("")
        self.canvas_trans.setObjectName("label_2")
        self.canvas_trans.setAlignment(QtCore.Qt.AlignLeft)
        self.gridLayout_3.addWidget(self.frame_24, 1, 0, 1, 2)
        self.tabWidget_2.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_21 = QtWidgets.QFrame(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_21.sizePolicy().hasHeightForWidth())
        self.frame_21.setSizePolicy(sizePolicy)
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_21)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem6)
        self.formLayout_16 = QtWidgets.QFormLayout()
        self.formLayout_16.setObjectName("formLayout_16")
        self._label10 = QtWidgets.QLabel(self.frame_21)
        self._label10.setObjectName("label_10")
        self.formLayout_16.setWidget(0, QtWidgets.QFormLayout.LabelRole, self._label10)
        self.scale_x = QtWidgets.QLineEdit(self.frame_21)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scale_x.sizePolicy().hasHeightForWidth())
        self.scale_x.setSizePolicy(sizePolicy)
        self.scale_x.setObjectName("lineEdit_10")
        self.formLayout_16.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.scale_x)
        self.horizontalLayout_11.addLayout(self.formLayout_16)
        self.formLayout_17 = QtWidgets.QFormLayout()
        self.formLayout_17.setObjectName("formLayout_17")
        self.label_21 = QtWidgets.QLabel(self.frame_21)
        self.label_21.setObjectName("label_21")
        self.formLayout_17.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.scale_y = QtWidgets.QLineEdit(self.frame_21)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scale_y.sizePolicy().hasHeightForWidth())
        self.scale_y.setSizePolicy(sizePolicy)
        self.scale_y.setObjectName("lineEdit_11")
        self.formLayout_17.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.scale_y)
        self.horizontalLayout_11.addLayout(self.formLayout_17)
        self.formLayout_18 = QtWidgets.QFormLayout()
        self.formLayout_18.setObjectName("formLayout_18")
        self.label_27 = QtWidgets.QLabel(self.frame_21)
        self.label_27.setObjectName("label_27")
        self.formLayout_18.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.horizontalLayout_11.addLayout(self.formLayout_18)
        self.scale_btn = QtWidgets.QPushButton(self.frame_21)
        self.scale_btn.setObjectName("pushButton_12")
        self.horizontalLayout_11.addWidget(self.scale_btn)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem7)
        self.gridLayout_4.addWidget(self.frame_21, 0, 1, 1, 1)
        self.frame_25 = QtWidgets.QFrame(self.tab_3)
        self.frame_25.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.canvas_scale = QtWidgets.QLabel(self.frame_25)
        self.canvas_scale.setGeometry(self.qrect_shape)
        self.canvas_scale.setText("")
        self.canvas_scale.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.frame_25, 1, 0, 1, 2)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_9)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_22 = QtWidgets.QFrame(self.tab_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_22.sizePolicy().hasHeightForWidth())
        self.frame_22.setSizePolicy(sizePolicy)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_22)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem8)
        self.formLayout_19 = QtWidgets.QFormLayout()
        self.formLayout_19.setObjectName("formLayout_19")
        self.label_28 = QtWidgets.QLabel(self.frame_22)
        self.label_28.setObjectName("label_28")
        self.formLayout_19.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.shear = QtWidgets.QLineEdit(self.frame_22)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shear.sizePolicy().hasHeightForWidth())
        self.shear.setSizePolicy(sizePolicy)
        self.shear.setObjectName("lineEdit_12")
        self.formLayout_19.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.shear)
        self.horizontalLayout_12.addLayout(self.formLayout_19)
        self.formLayout_20 = QtWidgets.QFormLayout()
        self.formLayout_20.setObjectName("formLayout_20")
        self.horizontalLayout_12.addLayout(self.formLayout_20)
        self.shear_btn = QtWidgets.QPushButton(self.frame_22)
        self.shear_btn.setObjectName("pushButton_13")
        self.horizontalLayout_12.addWidget(self.shear_btn)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem9)
        self.gridLayout_5.addWidget(self.frame_22, 0, 1, 1, 1)
        self.frame_26 = QtWidgets.QFrame(self.tab_9)
        self.frame_26.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.canvas_shear = QtWidgets.QLabel(self.frame_26)
        self.canvas_shear.setGeometry(self.qrect_shape)
        self.canvas_shear.setText("")
        self.canvas_shear.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.frame_26, 1, 0, 1, 2)
        self.tabWidget_2.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_10)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame_23 = QtWidgets.QFrame(self.tab_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_23.sizePolicy().hasHeightForWidth())
        self.frame_23.setSizePolicy(sizePolicy)
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_23)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem10)
        self.formLayout_21 = QtWidgets.QFormLayout()
        self.formLayout_21.setObjectName("formLayout_21")
        self.label_30 = QtWidgets.QLabel(self.frame_23)
        self.label_30.setObjectName("label_30")
        self.formLayout_21.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.rot_angle = QtWidgets.QLineEdit(self.frame_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rot_angle.sizePolicy().hasHeightForWidth())
        self.rot_angle.setSizePolicy(sizePolicy)
        self.rot_angle.setObjectName("lineEdit_13")
        self.formLayout_21.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.rot_angle)
        self.horizontalLayout_13.addLayout(self.formLayout_21)
        self.formLayout_22 = QtWidgets.QFormLayout()
        self.formLayout_22.setObjectName("formLayout_22")
        self.label_31 = QtWidgets.QLabel(self.frame_23)
        self.label_31.setObjectName("label_31")
        self.formLayout_22.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.horizontalLayout_13.addLayout(self.formLayout_22)
        self.rotate_btn = QtWidgets.QPushButton(self.frame_23)
        self.rotate_btn.setObjectName("pushButton_14")
        self.horizontalLayout_13.addWidget(self.rotate_btn)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem11)
        self.gridLayout_6.addWidget(self.frame_23, 0, 1, 1, 1)
        self.frame_27 = QtWidgets.QFrame(self.tab_10)
        self.frame_27.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.canvas_rotate = QtWidgets.QLabel(self.frame_27)
        self.canvas_rotate.setGeometry(self.qrect_shape)
        self.canvas_rotate.setText("")
        self.canvas_rotate.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.frame_27, 1, 0, 1, 2)
        self.tabWidget_2.addTab(self.tab_10, "")
        self.gridLayout.addWidget(self.tabWidget_2, 0, 0, 1, 1)
        self.tabWidget_2.setCurrentIndex(0)

        self.setLayout(self.gridLayout)
        self.retranslateUi()

        self.trans_x.textChanged.connect(lambda value: event_manager.trigger("on_update_transformation_param", value, "trans_x"))
        self.trans_y.textChanged.connect(lambda value: event_manager.trigger("on_update_transformation_param", value, "trans_y"))
        self.scale_x.textChanged.connect(lambda value: event_manager.trigger("on_update_transformation_param", value, "scale_x"))
        self.scale_y.textChanged.connect(lambda value: event_manager.trigger("on_update_transformation_param", value, "scale_y"))
        self.shear.textChanged.connect(lambda value: event_manager.trigger("on_update_transformation_param", value, "shear"))
        self.rot_angle.textChanged.connect(lambda value: event_manager.trigger("on_update_transformation_param", value, "rot_angle"))


        self.trans_btn.clicked.connect(lambda : event_manager.trigger("on_apply_transformation", "translate"))
        self.scale_btn.clicked.connect(lambda : event_manager.trigger("on_apply_transformation", "scale"))
        self.shear_btn.clicked.connect(lambda : event_manager.trigger("on_apply_transformation", "shear"))
        self.rotate_btn.clicked.connect(lambda : event_manager.trigger("on_apply_transformation", "rotate"))

        event_manager.register("on_image_loaded", self.update_canvas)



    def update_canvas(self, image, canvas):
        print("====UPDATING TRANSFORMATION CANVAS====")
        if image is None:
            return
        pixmap = np_array_to_pixmap(image)
        if canvas == "all":
            self.canvas_trans.setPixmap(pixmap)
            self.canvas_scale.setPixmap(pixmap)
            self.canvas_shear.setPixmap(pixmap)
            self.canvas_rotate.setPixmap(pixmap)
        
        if canvas == "translate":
            self.canvas_trans.setPixmap(pixmap)
        if canvas == "scale":
            self.canvas_scale.setPixmap(pixmap)
        if canvas == "shear":
            self.canvas_shear.setPixmap(pixmap)
        if canvas == "rotate":
            self.canvas_rotate.setPixmap(pixmap)


    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        # Lab4_Window.setWindowTitle(_translate("Lab4_Window", "Lab4_Window"))

        self.label_8.setText(_translate("Lab4_Window", "X"))
        self.trans_x.setText(_translate("Lab4_Window", "0"))
        self.label_9.setText(_translate("Lab4_Window", "Y"))
        self.trans_y.setText(_translate("Lab4_Window", "0"))
        self.trans_btn.setText(_translate("Lab4_Window", "Apply translation"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("Lab4_Window", "Translate"))
        self._label10.setText(_translate("Lab4_Window", "X"))
        self.scale_x.setText(_translate("Lab4_Window", "1.0"))
        self.label_21.setText(_translate("Lab4_Window", "Y"))
        self.scale_y.setText(_translate("Lab4_Window", "1.0"))
        self.scale_btn.setText(_translate("Lab4_Window", "Apply scale"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("Lab4_Window", "Scale"))
        self.label_28.setText(_translate("Lab4_Window", "Shear"))
        self.shear.setText(_translate("Lab4_Window", "1"))
        self.shear_btn.setText(_translate("Lab4_Window", "Apply shear"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_9), _translate("Lab4_Window", "Shear"))
        self.label_30.setText(_translate("Lab4_Window", "Angle (degrees)"))
        self.rot_angle.setText(_translate("Lab4_Window", "90.0"))
        self.rotate_btn.setText(_translate("Lab4_Window", "Apply rotate"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_10), _translate("Lab4_Window", "Rotate"))